name: food_otg_2025
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rename:
  get:
  google_fonts:
  pin_code_fields:
  cached_network_image:
  carousel_slider:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  flutter_local_notifications:
  geocoding:
  geolocator:
  location:
  lottie:
  shimmer:
  intl:
  flutter_rating_bar:
  flutter_vector_icons:
  flutter_screenutil:
  # razorpay_flutter:
  shared_preferences:
  google_maps_flutter:
  http:
  url_launcher:
  image_picker:
  flutter_ringtone_player:
  rxdart:
  vibration:
  logger:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/anime/
    - assets/foodly/
    - assets/icons/
    - assets/images/

fonts:
  - family: PALATIN1
    fonts:
      - asset: assets/fonts/PALATIN1.ttf
