name: food_otg_driver
description: "Food Otg Driver app."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rename: ^2.1.1
  get: ^4.6.5
  google_fonts: ^4.0.4
  cached_network_image: ^3.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  pin_code_fields: ^7.4.0
  image_picker: ^1.0.7
  geocoding: ^3.0.0
  geolocator:
  location: ^5.0.3
  firebase_messaging:
  flutter_local_notifications: ^17.2.3
  intl:
  flutter_rating_bar:
  flutter_vector_icons:
  flutter_screenutil:
  logger:
  sms_autofill: ^2.4.1
  another_telephony: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/new_logo_f.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/anime/
    - assets/foodly/
    - assets/icons/
    - assets/images/

fonts:
  - family: PALATIN1
    fonts:
      - asset: assets/fonts/PALATIN1.ttf
